name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test
      run: |
        ruby test_graph.rb
        ruby test_union_find.rb
        ruby test_n2m2_strategy.rb
        ruby test_n3m2_strategy.rb
        ruby test_n3m3_strategy.rb
